// Auto-generated Google Business Profile Local SEO Location Configuration
export const gbpLocation = {
  storeName: "Queensway Cannabis Dispensary",
  domain: "queenswaycannabisdispensary.com",
  city: "Etobicoke",
  province: "ON",
  country: "CA",
  slug: "weed-dispensary-etobicoke",
  address: "1174 The Queensway, Etobicoke, ON M8Z 1R5",
  streetAddress: "1174 The Queensway",
  postalCode: "M8Z 1R5",
  phone: "(437) 331-9109",
  phoneIntl: "+14373319109",
  neighborhood: "The Queensway / Etobicoke",
  nearbyAreas: ["The Queensway", "Etobicoke", "Islington", "Royal York", "Mimico", "Humber Bay", "Stonegate-Queensway", "TTC"],
  products: [
    "Flower",
    "Pre-rolls",
    "Edibles",
    "THC vapes",
    "Concentrates",
    "Shatter",
    "CBD oils",
    "Accessories"
  ],
  menuUrl: "/",
  directionsUrl: "https://www.google.com/maps/search/?api=1&query=1174%20The%20Queensway%2C%20Etobicoke%2C%20ON%20M8Z%201R5",
  mapEmbedUrl: "https://maps.google.com/maps?q=Queensway%20Cannabis%20Dispensary%201174%20The%20Queensway%2C%20Etobicoke%2C%20ON%20M8Z%201R5&t=&z=15&ie=UTF8&iwloc=&output=embed",
  latitude: "43.6223417",
  longitude: "-79.5217307",
  hours: ["Open Daily: 10:00 AM - 12:00 AM"],
  seoTitle: "Queensway Cannabis Dispensary | Weed Dispensary in Etobicoke",
  metaDescription: "Queensway Cannabis Dispensary is a local weed dispensary in Etobicoke offering flower, pre-rolls, edibles, vapes, concentrates, CBD, and service for adults 19+.",
  localLandmarks: ["The Queensway", "Etobicoke", "Islington"],
  introVariant: "Welcome to Queensway Cannabis Dispensary, your premier weed dispensary in Etobicoke situated right on 1174 The Queensway. We are dedicated to providing adults 19+ with top-tier weed, premium cannabis flower, pre-rolls, edibles, THC vapes, concentrates, and CBD products. If you are looking for a trusted cannabis store near The Queensway / Etobicoke or a weed shop near Etobicoke, stop by today to consult with our knowledgeable staff.",
  neighborhoodDescription: "Located in the vibrant The Queensway / Etobicoke district, our cannabis store fits right into this active and historic community, surrounded by local retail shops and convenient transit links.",
  parkingNote: "Street parking and local retail lot parking are available nearby",
  transitNote: "Accessible by local TTC bus routes along The Queensway.",
  sectionTitle: "Serving Customers Near The Queensway and Etobicoke"
};
